
name: bukkapay_mobile
description: BukkaPay Mobile Wallet Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  lucide_icons: ^0.3.0
  http: ^1.2.0
  shared_preferences: ^2.2.0
  provider: ^6.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
